import Feed from "./Feed";
import Navbar from "./Navbar";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Rifqi Showroom",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Epilogue:wght@200;300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Toaster position="top-center" reverseOrder={false} />
        <nav className="w-10/12 float-right">
          <Navbar />
        </nav>
        <aside>
          <Feed />
        </aside>
        <main className="w-10/12 float-right">{children}</main>
      </body>
    </html>
  );
}
